export const BASE_URL = "https://172.30.1.4:8443/qleaca/api";

export const COMMON_CONFIG = "COMMON_CONFIG";

export enum loginTypes {
    FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST",
    FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS",
    FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE",
    LOGGED_INFO = "LOGGED_INFO",
  }

export enum roleTypes {
  FETCH_ROLE_REQUEST = "FETCH_ROLE_REQUEST",
  FETCH_ROLE_SUCCESS = "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILURE = "FETCH_ROLE_FAILURE",
  ROLE_INFO = "ROLE_INFO",
}
